### ISSUE TITLE
Latest goldendict doesn't compile with Qt5 on Lubuntu 14.04

### ISSUE THREAD

**Issue by vedgy** [goldendict/goldendict#990]
I was trying to test my fix for #645 with an older Qt5 version. But couldn't even compile current goldendict master.

*1.* The [QString::indexOf() overload with 3 arguments](https://doc.qt.io/qt-5/qstring.html#indexOf-7) was introduced in Qt 5.5 according to the documentation. I replaced `#if QT_VERSION >= QT_VERSION_CHECK( 5, 0, 0 )` with `#if QT_VERSION >= QT_VERSION_CHECK( 5, 5, 0 )` on line 1026 of file *mdx.cc* to fix compilation.

*2.* Another issue is that Ubuntu 14.04 has different QtBase and QtWebKit versions - 5.2 and 5.1 respectively: https://packages.ubuntu.com/search?suite=trusty&arch=any&searchon=names&keywords=qt5w

Could the `SecurityWhiteList` and `AllowFrameReply` workarounds be made optional or require Qt 5.3? If the workarounds were optional, I'd probably disable them on my system as well to avoid issues discussed in #968, unless the workarounds are useful for MediaWiki sites I use.

Of course, Ubuntu 14.04 is 4 years old, so goldendict does not have to support it fully. The Qt4 version will probably work there. On the other hand, there is little reason to support the workaround with Qt 5.2, especially considering that the oldest supported Qt5 version on Debian is 5.3: https://packages.debian.org/search?searchon=names&keywords=qt5webkit
I guess most Qt 5.2 users also use Ubuntu 14.04, so they would rather have the workaround disabled :)
I simply replaced `502` with `503` in *article_netmgr.\**, and compilation succeeded.

Compiler output:
> ../article_netmgr.cc: In member function ‘QWebSecurityOrigin* SecurityWhiteList::setOrigin(const QUrl&)’:
../article_netmgr.cc:34:42: error: no matching function for call to ‘QWebSecurityOrigin::QWebSecurityOrigin(const QUrl&)’
     origin = new QWebSecurityOrigin( url );
                                          ^
../article_netmgr.cc:34:42: note: candidates are:
In file included from /usr/include/qt5/QtWebKit/QWebSecurityOrigin:1:0,
                 from ../article_netmgr.hh:10,
                 from ../article_netmgr.cc:12:
/usr/include/qt5/QtWebKit/qwebsecurityorigin.h:64:5: note: QWebSecurityOrigin::QWebSecurityOrigin(QWebSecurityOriginPrivate*)
     QWebSecurityOrigin(QWebSecurityOriginPrivate* priv);
     ^
/usr/include/qt5/QtWebKit/qwebsecurityorigin.h:64:5: note:   no known conversion for argument 1 from ‘const QUrl’ to ‘QWebSecurityOriginPrivate*’
/usr/include/qt5/QtWebKit/qwebsecurityorigin.h:58:5: note: QWebSecurityOrigin::QWebSecurityOrigin(const QWebSecurityOrigin&)
     QWebSecurityOrigin(const QWebSecurityOrigin& other);
     ^
/usr/include/qt5/QtWebKit/qwebsecurityorigin.h:58:5: note:   no known conversion for argument 1 from ‘const QUrl’ to ‘const QWebSecurityOrigin&’
../article_netmgr.cc: In member function ‘void SecurityWhiteList::swlCopy(const SecurityWhiteList&)’:
../article_netmgr.cc:44:58: error: no matching function for call to ‘QWebSecurityOrigin::QWebSecurityOrigin(QUrl)’
       origin = new QWebSecurityOrigin( QUrl( originUri ) );
                                                          ^
../article_netmgr.cc:44:58: note: candidates are:
In file included from /usr/include/qt5/QtWebKit/QWebSecurityOrigin:1:0,
                 from ../article_netmgr.hh:10,
                 from ../article_netmgr.cc:12:
/usr/include/qt5/QtWebKit/qwebsecurityorigin.h:64:5: note: QWebSecurityOrigin::QWebSecurityOrigin(QWebSecurityOriginPrivate*)
     QWebSecurityOrigin(QWebSecurityOriginPrivate* priv);
     ^
/usr/include/qt5/QtWebKit/qwebsecurityorigin.h:64:5: note:   no known conversion for argument 1 from ‘QUrl’ to ‘QWebSecurityOriginPrivate*’
/usr/include/qt5/QtWebKit/qwebsecurityorigin.h:58:5: note: QWebSecurityOrigin::QWebSecurityOrigin(const QWebSecurityOrigin&)
     QWebSecurityOrigin(const QWebSecurityOrigin& other);
     ^
/usr/include/qt5/QtWebKit/qwebsecurityorigin.h:58:5: note:   no known conversion for argument 1 from ‘QUrl’ to ‘const QWebSecurityOrigin&’
../article_netmgr.cc:48:17: error: ‘class QWebSecurityOrigin’ has no member named ‘addAccessWhitelistEntry’
         origin->addAccessWhitelistEntry( it->first, it->second, QWebSecurityOrigin::AllowSubdomains );
                 ^
../article_netmgr.cc:48:65: error: ‘AllowSubdomains’ is not a member of ‘QWebSecurityOrigin’
         origin->addAccessWhitelistEntry( it->first, it->second, QWebSecurityOrigin::AllowSubdomains );
                                                                 ^
../article_netmgr.cc: In member function ‘void SecurityWhiteList::swlDelete()’:
../article_netmgr.cc:58:17: error: ‘class QWebSecurityOrigin’ has no member named ‘removeAccessWhitelistEntry’
         origin->removeAccessWhitelistEntry( it->first, it->second, QWebSecurityOrigin::AllowSubdomains );
                 ^
../article_netmgr.cc:58:68: error: ‘AllowSubdomains’ is not a member of ‘QWebSecurityOrigin’
         origin->removeAccessWhitelistEntry( it->first, it->second, QWebSecurityOrigin::AllowSubdomains );
                                                                    ^
../article_netmgr.cc: In member function ‘void AllowFrameReply::applyMetaData()’:
../article_netmgr.cc:163:19: error: ‘SpdyWasUsedAttribute’ is not a member of ‘QNetworkRequest’
     setAttribute( QNetworkRequest::SpdyWasUsedAttribute,
                   ^
../article_netmgr.cc:164:41: error: ‘SpdyWasUsedAttribute’ is not a member of ‘QNetworkRequest’
                   baseReply->attribute( QNetworkRequest::SpdyWasUsedAttribute ) );
                                         ^
../article_netmgr.cc: In member function ‘virtual QNetworkReply* ArticleNetworkAccessManager::createRequest(QNetworkAccessManager::Operation, const QNetworkRequest&, QIODevice*)’:
../article_netmgr.cc:284:27: error: ‘class QWebSecurityOrigin’ has no member named ‘addAccessWhitelistEntry’
             value.origin->addAccessWhitelistEntry( target.first, target.second,
                           ^
../article_netmgr.cc:285:52: error: ‘AllowSubdomains’ is not a member of ‘QWebSecurityOrigin’
                                                    QWebSecurityOrigin::AllowSubdomains );
                                                    ^

**Comment by Abs62** [comment]
Fixed, try now.

**Comment by vedgy** [comment]
Still doesn't compile. `502` has to be replaced with `503` in 5 more places in *article_netmgr.hh* and *article_netmgr.cc*. Alternatively a new preprocessor definition can be added in *article_netmgr.hh* for Qt5.3+, then used in these 6 places, to avoid Qt version inconsistency mistakes in the future.

**Comment by Abs62** [comment]
OK, fixed.

**Comment by vedgy** [comment]
Compiles now.
